name: profile-dataset
version: "1.0.0"
description: Profile CSV datasets with statistics and type inference

tags:
  - data
  - profiling

triggers:
  - Profile a CSV file
  - Generate dataset statistics

dependencies: []

command:
  binary: skillpack
  subcommand: profile-dataset
  template: "skillpack profile-dataset --csv data.csv"

arguments:
  csv:
    type: path
    required: true
    cli_name: "--csv"
    description: "Path to the CSV file to profile"

output:
  directory: "./out/profile_dataset/"
  files:
    - profile.md
    - profile.json
