name: profile-dataset
version: "1.0.0"
description: Profile CSV datasets.
tags:
  - automation
  - data

triggers:
  - Generate profile-dataset output
  - Create profile dataset

dependencies: []

command:
  binary: skillpack
  subcommand: profile-dataset
  template: "skillpack profile-dataset --csv {...}"

arguments:
  csv:
    type: string
    required: false
    cli_name: "--csv"
    description: "Path to the CSV file to profile"

output:
  directory: "./out/profile_dataset/"
  files:
    - output.md
