name: daily-ops-summary
version: "1.0.0"
description: Generate daily status report from pipeline and system health

tags:
  - operations
  - reporting

triggers:
  - Generate daily ops summary
  - Create operations report

dependencies: []

command:
  binary: skillpack
  subcommand: daily-ops-summary
  template: "skillpack daily-ops-summary --date 2024-01-15"

arguments:
  date:
    type: string
    required: false
    cli_name: "--date"
    description: "Date for summary (YYYY-MM-DD), defaults to today"
  metrics:
    type: path
    required: false
    cli_name: "--metrics"
    description: "Path to metrics YAML file"
  team:
    type: string
    required: false
    cli_name: "--team"
    description: "Team name for the report (default: Data Platform)"
  output_dir:
    type: path
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/daily_ops_summary/"
  files:
    - "ops_summary_{date}.md"
    - "slack_message_{date}.txt"
    - "metrics_{date}.yaml"
