name: pr-summary
version: "1.0.0"
description: Generate PR summaries with risk assessment from diffs.
tags:
  - automation
  - data

triggers:
  - Generate pr-summary output
  - Create pr summary

dependencies: []

command:
  binary: skillpack
  subcommand: pr-summary
  template: "skillpack pr-summary --diff-file {...} --title {...}"

arguments:
  diff_file:
    type: string
    required: false
    cli_name: "--diff-file"
    description: "Path to the diff file to analyze"
  title:
    type: string
    required: false
    cli_name: "--title"
    description: "Title for the summary (default: "

output:
  directory: "./out/pr_summary/"
  files:
    - output.md
