name: dbt-generator
version: "1.0.0"
description: Generate dbt models and tests

tags:
  - data
  - dbt

triggers:
  - Generate dbt models
  - Create dbt staging and marts

dependencies: []

command:
  binary: skillpack
  subcommand: dbt-generator
  template: "skillpack dbt-generator --config config.yaml"

arguments:
  config:
    type: path
    required: false
    cli_name: "--config"
    description: "Path to config file (YAML or JSON). If not provided, generates an example."

output:
  directory: "./out/dbt_generator/"
  files:
    - models/staging/stg_*.sql
    - models/marts/*.sql
    - models/schema.yml
    - models/docs.md
