name: dbt-generator
version: "1.0.0"
description: Generate dbt models and tests.
tags:
  - automation
  - data

triggers:
  - Generate dbt-generator output
  - Create dbt generator

dependencies: []

command:
  binary: skillpack
  subcommand: dbt-generator
  template: "skillpack dbt-generator --config {...}"

arguments:
  config:
    type: string
    required: false
    cli_name: "--config"
    description: "Path to config file (YAML or JSON). If not provided, generates an example."

output:
  directory: "./out/dbt_generator/"
  files:
    - output.md
