name: fastapi-serving
version: "1.0.0"
description: Wrap models in FastAPI services with validation and health endpoints.
tags:
  - automation
  - data

triggers:
  - Generate fastapi-serving output
  - Create fastapi serving

dependencies: []

command:
  binary: skillpack
  subcommand: fastapi-serving
  template: "skillpack fastapi-serving --name {...} --type {...} --output-dir {...}"

arguments:
  name:
    type: string
    required: false
    cli_name: "--name"
    description: "Model/service name"
  type:
    type: string
    required: false
    cli_name: "--type"
    description: "Model type"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/fastapi_serving/"
  files:
    - main.py
    - schemas.py
    - Dockerfile
    - requirements.txt
    - test_api.py
