name: project-scaffolding
version: "1.0.0"
description: Generate new project skeletons.
tags:
  - automation
  - data

triggers:
  - Generate project-scaffolding output
  - Create project scaffolding

dependencies: []

command:
  binary: skillpack
  subcommand: project-scaffolding
  template: "skillpack project-scaffolding --name {...} --description {...}"

arguments:
  name:
    type: string
    required: false
    cli_name: "--name"
    description: "Name of the project to create"
  description:
    type: string
    required: false
    cli_name: "--description"
    description: "Project description (default: "

output:
  directory: "./out/project_scaffolding/"
  files:
    - output.md
