name: iac-boilerplate
version: "1.0.0"
description: Generate Terraform modules for cloud infrastructure.
tags:
  - automation
  - data

triggers:
  - Generate iac-boilerplate output
  - Create iac boilerplate

dependencies: []

command:
  binary: skillpack
  subcommand: iac-boilerplate
  template: "skillpack iac-boilerplate --name {...} --cloud {...} --resources {...}"

arguments:
  name:
    type: string
    required: false
    cli_name: "--name"
    description: "Project name"
  cloud:
    type: string
    required: false
    cli_name: "--cloud"
    description: "Cloud provider"
  resources:
    type: string
    required: false
    cli_name: "--resources"
    description: "Comma-separated resources to generate"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/iac_boilerplate/"
  files:
    - main.tf
    - variables.tf
    - outputs.tf
    - main.tf
    - terraform.tfvars.example
