name: evaluation-report
version: "1.0.0"
description: Generate model evaluation reports with metrics and plots.
tags:
  - automation
  - data

triggers:
  - Generate evaluation-report output
  - Create evaluation report

dependencies: []

command:
  binary: skillpack
  subcommand: evaluation-report
  template: "skillpack evaluation-report --name {...} --task {...} --metrics {...}"

arguments:
  name:
    type: string
    required: false
    cli_name: "--name"
    description: "Model name"
  task:
    type: string
    required: false
    cli_name: "--task"
    description: "Task type"
  metrics:
    type: string
    required: false
    cli_name: "--metrics"
    description: "Path to metrics YAML file"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/evaluation_report/"
  files:
    - evaluation_report.md
    - evaluate.py
    - plot_results.py
    - metrics.yaml
