# sql-refiner
version: "1.0.0"
description: Generate SQL queries from natural language with dialect-specific syntax
tags: [sql, query, postgres, bigquery, snowflake]

triggers:
  - "write sql"
  - "generate query"
  - "sql from question"

dependencies: []

command:
  binary: skillpack
  subcommand: sql-refiner
  template: "skillpack sql-refiner --question {question} --dialect {dialect}"

arguments:
  question:
    type: string
    required: true
    cli_name: "--question"
    description: Natural language question
  dialect:
    type: enum
    required: false
    cli_name: "--dialect"
    default: postgres
    values: [postgres, bigquery, snowflake]

output:
  directory: "./out/sql_refiner/"
  files:
    - query.sql
    - explain.sql
    - query_notes.md
