name: sql-refiner
version: "1.0.0"
description: Generate SQL from natural language questions

tags:
  - sql
  - data

triggers:
  - Generate SQL query
  - Convert question to SQL

dependencies: []

command:
  binary: skillpack
  subcommand: sql-refiner
  template: "skillpack sql-refiner --question 'How many active users?' --dialect postgres"

arguments:
  question:
    type: string
    required: true
    cli_name: "--question"
    description: "Natural language question to convert to SQL"
  dialect:
    type: string
    required: false
    cli_name: "--dialect"
    description: "SQL dialect: postgres, bigquery, or snowflake"

output:
  directory: "./out/sql_refiner/"
  files:
    - query.sql
    - explain.sql
    - query_notes.md
