name: sql-refiner
version: "1.0.0"
description: Generate SQL queries from natural language questions.
tags:
  - automation
  - data

triggers:
  - Generate sql-refiner output
  - Create sql refiner

dependencies: []

command:
  binary: skillpack
  subcommand: sql-refiner
  template: "skillpack sql-refiner --question {...} --dialect {...}"

arguments:
  question:
    type: string
    required: false
    cli_name: "--question"
    description: "Natural language question to convert to SQL"
  dialect:
    type: string
    required: false
    cli_name: "--dialect"
    description: "SQL dialect (default: postgres)"

output:
  directory: "./out/sql_refiner/"
  files:
    - output.md
