name: experiment-queue
version: "1.0.0"
description: Manage experiment queue with checkpointing.
tags:
  - automation
  - ml

triggers:
  - Generate experiment-queue output
  - Create experiment queue

dependencies: []

command:
  binary: skillpack
  subcommand: experiment-queue
  template: "skillpack experiment-queue --name {...} --output-dir {...} --config {...}"

arguments:
  name:
    type: string
    required: false
    cli_name: "--name"
    description: "Queue name"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"
  config:
    type: string
    required: false
    cli_name: "--config"
    description: "Resume from checkpoint"
  status:
    type: string
    required: false
    cli_name: "--status"
    description: "Show queue status"

output:
  directory: "./out/experiment_queue/"
  files:
    - queue_manager.py
    - run_queue.py
    - experiments.yaml
    - checkpoint.json
