name: data-quality
version: "1.0.0"
description: Generate Pandera validation schemas.
tags:
  - automation
  - data

triggers:
  - Generate data-quality output
  - Create data quality

dependencies:
  - profile-dataset

command:
  binary: skillpack
  subcommand: data-quality
  template: "skillpack data-quality --config {...}"

arguments:
  config:
    type: string
    required: false
    cli_name: "--config"
    description: "Path to config file (YAML or JSON). If not provided, generates an example."

output:
  directory: "./out/data_quality/"
  files:
    - output.md
