name: data-quality
version: "1.0.0"
description: Generate Pandera validation schemas

tags:
  - data
  - validation

triggers:
  - Generate data quality schema
  - Create validation script

dependencies:
  - profile-dataset

command:
  binary: skillpack
  subcommand: data-quality
  template: "skillpack data-quality --config schema_config.yaml"

arguments:
  config:
    type: path
    required: false
    cli_name: "--config"
    description: "Path to config file (YAML/JSON). If not provided, generates example."

output:
  directory: "./out/data_quality/"
  files:
    - schema.py
    - run_validation.py
