name: dag-authoring
version: "1.0.0"
description: Generate DAG code for Airflow, Prefect, or Dagster

tags:
  - automation
  - orchestration

triggers:
  - Generate orchestration DAG
  - Create Airflow/Prefect/Dagster pipeline

dependencies: []

command:
  binary: skillpack
  subcommand: dag-authoring
  template: "skillpack dag-authoring --name {name} --framework airflow"

arguments:
  name:
    type: string
    required: true
    cli_name: "--name"
    description: "DAG/Flow name"
  framework:
    type: string
    required: false
    cli_name: "--framework"
    description: "Target framework: airflow, prefect, or dagster"
  schedule:
    type: string
    required: false
    cli_name: "--schedule"
    description: "Schedule expression (e.g., @daily)"
  output_dir:
    type: path
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/dag_authoring/"
  files:
    - "{name}_dag.py"
    - "{name}_runbook.md"
