name: dag-authoring
version: "1.0.0"
description: Generate DAG code for Airflow, Prefect, or Dagster.
tags:
  - automation
  - data

triggers:
  - Generate dag-authoring output
  - Create dag authoring

dependencies: []

command:
  binary: skillpack
  subcommand: dag-authoring
  template: "skillpack dag-authoring --name {...} --framework {...} --config {...}"

arguments:
  name:
    type: string
    required: false
    cli_name: "--name"
    description: "DAG/Flow name"
  framework:
    type: string
    required: false
    cli_name: "--framework"
    description: "Target orchestration framework"
  config:
    type: string
    required: false
    cli_name: "--config"
    description: "Path to pipeline configuration YAML"
  schedule:
    type: string
    required: false
    cli_name: "--schedule"
    description: "Schedule expression (e.g., @daily, 0 0 * * *)"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/dag_authoring/"
  files:
    - output.md
