name: schema-diff
version: "1.0.0"
description: Compare schemas and generate migrations.
tags:
  - automation
  - data

triggers:
  - Generate schema-diff output
  - Create schema diff

dependencies: []

command:
  binary: skillpack
  subcommand: schema-diff
  template: "skillpack schema-diff --old {...} --new {...} --table {...}"

arguments:
  old:
    type: string
    required: false
    cli_name: "--old"
    description: "Path to old schema JSON file"
  new:
    type: string
    required: false
    cli_name: "--new"
    description: "Path to new schema JSON file"
  table:
    type: string
    required: false
    cli_name: "--table"
    description: "Table name for the migration (default: table_name)"

output:
  directory: "./out/schema_diff/"
  files:
    - output.md
