name: schema-diff
version: "1.0.0"
description: Compare schemas and generate migrations

tags:
  - database
  - migration

triggers:
  - Compare database schemas
  - Generate migration SQL

dependencies: []

command:
  binary: skillpack
  subcommand: schema-diff
  template: "skillpack schema-diff --old old_schema.json --new new_schema.json"

arguments:
  old:
    type: path
    required: true
    cli_name: "--old"
    description: "Path to old schema JSON file"
  new:
    type: path
    required: true
    cli_name: "--new"
    description: "Path to new schema JSON file"
  table:
    type: string
    required: false
    cli_name: "--table"
    description: "Table name for the migration (default: table_name)"

output:
  directory: "./out/schema_diff/"
  files:
    - migration.sql
    - migration.md
