name: quality-gate
version: "1.0.0"
description: Run format + lint + type-check + tests.
tags:
  - automation
  - data

triggers:
  - Generate quality-gate output
  - Create quality gate

dependencies: []

command:
  binary: skillpack
  subcommand: quality-gate
  template: "skillpack quality-gate --check {...}"

arguments:
  check:
    type: string
    required: false
    cli_name: "--check"
    description: "Check only, don"

output:
  directory: "./out/quality_gate/"
  files:
    - output.md
