name: quality-gate
version: "1.0.0"
description: Run format + lint + type-check + tests

tags:
  - quality
  - ci

triggers:
  - Run quality checks
  - Validate code quality

dependencies: []

command:
  binary: skillpack
  subcommand: quality-gate
  template: "skillpack quality-gate --check"

arguments:
  check:
    type: boolean
    required: false
    cli_name: "--check"
    description: "Check only, don't modify files"

output:
  directory: null
  files: []
  note: "Writes to stdout only, no file output"
