name: feature-engineering
version: "1.0.0"
description: Suggest and generate feature transformations per column type.
tags:
  - automation
  - data

triggers:
  - Generate feature-engineering output
  - Create feature engineering

dependencies: []

command:
  binary: skillpack
  subcommand: feature-engineering
  template: "skillpack feature-engineering --config {...} --output-dir {...}"

arguments:
  config:
    type: string
    required: false
    cli_name: "--config"
    description: "Path to column configuration YAML"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/feature_engineering/"
  files:
    - features.py
    - transformations.md
    - feature_config.yaml
