name: feature-engineering
version: "1.0.0"
description: Suggest and generate feature transformations per column type
tags: []

triggers:
  - "TODO: add natural language triggers"

dependencies: []

command:
  binary: skillpack
  subcommand: feature-engineering
  template: "skillpack feature-engineering --input {input_path}"

arguments:
  input_path:
    type: file_path
    required: true
    cli_name: "--input"
    description: Input file path

output:
  directory: "./out/feature_engineering/"
  files:
    - output.txt
