name: test-writer
version: "1.0.0"
description: Generate pytest tests from code.
tags:
  - automation
  - data

triggers:
  - Generate test-writer output
  - Create test writer

dependencies: []

command:
  binary: skillpack
  subcommand: test-writer
  template: "skillpack test-writer --source {...} --output-dir {...}"

arguments:
  source:
    type: string
    required: false
    cli_name: "--source"
    description: "Path to Python source file"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/test_writer/"
  files:
    - conftest.py
