name: monitoring-drift
version: "1.0.0"
description: Generate data and prediction drift detection templates.
tags:
  - automation
  - data

triggers:
  - Generate monitoring-drift output
  - Create monitoring drift

dependencies: []

command:
  binary: skillpack
  subcommand: monitoring-drift
  template: "skillpack monitoring-drift --name {...} --type {...} --output-dir {...}"

arguments:
  name:
    type: string
    required: false
    cli_name: "--name"
    description: "Model/dataset name"
  type:
    type: string
    required: false
    cli_name: "--type"
    description: "Type of drift to monitor"
  output_dir:
    type: string
    required: false
    cli_name: "--output-dir"
    description: "Output directory"

output:
  directory: "./out/monitoring_drift/"
  files:
    - data_drift.py
    - prediction_drift.py
    - alerting.yaml
    - dashboard.json
    - README.md
